"""empty message

Revision ID: 0b77f29b8791
Revises: d07ae470b948
Create Date: 2019-04-23 00:30:18.079785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b77f29b8791'
down_revision = 'd07ae470b948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('appointment_date', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'appointment_date')
    # ### end Alembic commands ###
