"""empty message

Revision ID: 11d61b24f875
Revises: 4ab37e23e043
Create Date: 2019-04-20 23:46:54.607177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11d61b24f875'
down_revision = '4ab37e23e043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_information', sa.Column('created_on', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_information', 'created_on')
    # ### end Alembic commands ###
