"""empty message

Revision ID: 7e7e9bbc1ff4
Revises: 7e53820d5fca
Create Date: 2019-04-22 20:16:52.803449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7e9bbc1ff4'
down_revision = '7e53820d5fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_information', sa.Column('usertype', sa.String(length=100), nullable=True))
    op.drop_column('employee_information', 'user_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_information', sa.Column('user_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('employee_information', 'usertype')
    # ### end Alembic commands ###
