"""empty message

Revision ID: c9d019427861
Revises: 7e7e9bbc1ff4
Create Date: 2019-04-22 22:18:33.511433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d019427861'
down_revision = '7e7e9bbc1ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_information', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_information', sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
