"""empty message

Revision ID: cf431fc6abd0
Revises: e425c9cb07c6
Create Date: 2019-04-19 00:07:50.912583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf431fc6abd0'
down_revision = 'e425c9cb07c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('user_type', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('customer_information', sa.Column('phoneNum', sa.String(length=80), nullable=True))
    op.drop_column('customer_information', 'username')
    op.drop_column('customer_information', 'user_type')
    op.drop_column('customer_information', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_information', sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('customer_information', sa.Column('user_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('customer_information', sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('customer_information', 'phoneNum')
    op.drop_table('employee_information')
    # ### end Alembic commands ###
