"""empty message

Revision ID: d07ae470b948
Revises: b039f445c576
Create Date: 2019-04-22 22:48:30.424730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd07ae470b948'
down_revision = 'b039f445c576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ac_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ac_type', sa.String(length=257), nullable=True),
    sa.Column('ac_issue', sa.String(length=257), nullable=True),
    sa.Column('unit_service', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ac_units')
    # ### end Alembic commands ###
