"""empty message

Revision ID: e0852b7baf07
Revises: 33303d233da5
Create Date: 2019-04-23 01:09:54.121135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0852b7baf07'
down_revision = '33303d233da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ac_units', sa.Column('acissue', sa.String(length=257), nullable=True))
    op.add_column('ac_units', sa.Column('actype', sa.String(length=257), nullable=True))
    op.add_column('ac_units', sa.Column('service', sa.String(length=200), nullable=True))
    op.drop_column('ac_units', 'ac_type')
    op.drop_column('ac_units', 'ac_issue')
    op.drop_column('ac_units', 'unit_service')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ac_units', sa.Column('unit_service', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('ac_units', sa.Column('ac_issue', sa.VARCHAR(length=257), autoincrement=False, nullable=True))
    op.add_column('ac_units', sa.Column('ac_type', sa.VARCHAR(length=257), autoincrement=False, nullable=True))
    op.drop_column('ac_units', 'service')
    op.drop_column('ac_units', 'actype')
    op.drop_column('ac_units', 'acissue')
    # ### end Alembic commands ###
