"""empty message

Revision ID: e425c9cb07c6
Revises: c4a0e5238796
Create Date: 2019-04-18 21:07:33.368648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e425c9cb07c6'
down_revision = 'c4a0e5238796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_information', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('customer_information', sa.Column('password', sa.String(length=80), nullable=True))
    op.add_column('customer_information', sa.Column('user_type', sa.String(length=100), nullable=True))
    op.add_column('customer_information', sa.Column('username', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_information', 'username')
    op.drop_column('customer_information', 'user_type')
    op.drop_column('customer_information', 'password')
    op.drop_column('customer_information', 'address')
    # ### end Alembic commands ###
